### ISSUE TITLE
ERROR (org.alfresco.solr.AlfrescoCoreAdminHandler@704b2127_Worker-20) [   ] o.a.s.t.AbstractTracker [alfresco / NODE_STATE_PUBLISHER@1048875139 / IT #1732624730002] Tracking failure. See the stacktrace below for further details. org.alfresco.error.AlfrescoRuntimeException: 10260115 GetTransactions return status is 404

### ISSUE THREAD

**Issue by desko12** [desko12/alfresco#1]
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: Ident authentication failed for user "alfresco")

**Comment by desko12** [comment]
this error indicates that the alfresco application has not been deployed correctly. You need to check the tomcat logs and specifically the application logs to see.
if you don't see anything in the tomcat logs and there are no logs linked to the application, you'll need to configure log4j to create the application log file.

To do this, you need to modify the following file:

```bash
export ALFRESCO_HOME=/srv/alfresco/
sed -i "s|^appender\.rolling\.fileName=alfresco\.log|appender.rolling.fileName=${ALFRESCO_HOME}/tomcat/logs/alfresco.log|" $ALFRESCO_HOME/tomcat/webapps/alfresco/WEB-INF/classes/log4j2.properties
sed -i "s|^appender\.rolling\.fileName=share\.log|appender.rolling.fileName=${ALFRESCO_HOME}/tomcat/logs/share.log|" $ALFRESCO_HOME/tomcat/webapps/share/WEB-INF/classes/log4j2.properties
```
Then restart tomcat 
`
sudo systemctl restart tomcat`

Then check the application log file as follows:

```
sudo tail -f $ALFRESCO_HOME/tomcat/logs/alfresco.log

Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:84) ~[spring-jdbc-6.0.14.jar:6.0.14]
        at org.alfresco.repo.domain.dialect.DialectFactoryBean.getObject(DialectFactoryBean.java:59) ~[alfresco-repository-23.2.0.60.jar:23.2.0.60]
        at org.alfresco.repo.domain.dialect.DialectFactoryBean.getObject(DialectFactoryBean.java:1) ~[alfresco-repository-23.2.0.60.jar:23.2.0.60]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:120) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:365) ~[spring-beans-6.0.14.jar:6.0.14]
        ... 59 more
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: Ident authentication failed for user "alfresco")
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:653) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:531) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:731) ~[commons-dbcp2-2.9.0.jar:2.9.0]
        at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:160) ~[spring-jdbc-6.0.14.jar:6.0.14]
        at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:118) ~[spring-jdbc-6.0.14.jar:6.0.14]
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81) ~[spring-jdbc-6.0.14.jar:6.0.14]
        at org.alfresco.repo.domain.dialect.DialectFactoryBean.getObject(DialectFactoryBean.java:59) ~[alfresco-repository-23.2.0.60.jar:23.2.0.60]
        at org.alfresco.repo.domain.dialect.DialectFactoryBean.getObject(DialectFactoryBean.java:1) ~[alfresco-repository-23.2.0.60.jar:23.2.0.60]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:178) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:120) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1804) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1273) ~[spring-beans-6.0.14.jar:6.0.14]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1791) ~[spring-beans-6.0.14.jar:6.0.14]
```

this error indicates that the application has not been deployed because it cannot reach the database. We will use the authentication parameters in the file to try to connect to the database. ($ALFRESCO_HOME/tomcat/shared/classes/alfresco-global.properties)

the syntax for connecting to the database is as follows:
`
psql -U username -W -d base_donnée
`

the **-W** option is used to request the pass mode.

if you get the following error:

psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "alfresco"

you need to modify the pg_hba.conf in the /var/lib/pgsql/data directory and replace the following elements with what will allow the connection to be authorised locally:

```
local   all             all                                    *peer* par *md5*
# IPv4 local connections:
host    all             all             127.0.0.1/32           *ident* par *md5*
# IPv6 local connections:
host    all             all             ::1/128                *ident* par *md5*
```
Then restart postgres service 
```
sudo systemctl restart postgresql.
```

then run the DB connection command again and enter your password. You will get this prompt, which means that the connection was successful.

```bash
root@desko-acs-2:/var/lib/pgsql/data# psql -U alfresco -W -d alfresco
Password: 
psql (16.4)
Type "help" for help.

alfresco=> exit
```

finally, restart the tomcat and solr service 

```
sudo systemctl restart tomcat solr
sudo systemctl status tomcat solr 
```
vous pouvez maintenant acceder à l'application alfresco.
